# Site settings
title: Joel Collins
email: firstnamelastname@gmail.com
description: "Joel's thoughts on programming and other things that interest him at the moment."
baseurl: ""
url: "http://joelcollinsdc.github.io"
twitter_username: joelcollinsdc
github_username:  joelcollinsdc

# Build settings
markdown: kramdown
permalink: pretty
