# Site settings
title: Joel Collins
email: firstnamelastname@gmail.com
description: "Joel's Internet Thoughts"
baseurl: ""
url: "http://joelcollinsdc.github.io"
twitter_username: joelcollinsdc
github_username:  joelcollinsdc

# Build settings
markdown: kramdown
permalink: pretty
